### ISSUE TITLE
DllImportAttribute TypeReference Skipped

### ISSUE THREAD

**Issue by NArnott** [jbevain/cecil#244]
When I call `AssemblyDefinition.ReadAssembly(stream)` on an assembly that uses `DllImportAttribute` and then `module.GetTypeReferences()`, for some reason `DllImportAttribute` in particular is not listed.  It also does not show up in any of the `MethodDefinition.CustomAttributes` for the methods that `DllImportAttribute` was applied to.

As a side note, I'm concerned that if this attribute is getting skipped, maybe others are getting skipped as well. 

I've confirmed that in my case, .NET Reflector does show the DllImportAttribute as expected.

If it helps, one example DllImport implemetation I'm testing with is provided below:
 
    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    public static extern int MessageBox(IntPtr hWnd, String text, String caption, uint type);

**Comment by jbevain** [comment]
Hey @NArnott!

That's because DllImportAttributes are not really attributes :) They're compiled not as a custom attribute but they have their special encoding. .NET Reflector transforms that back to an attribute when decompiling to C#.

You can check that a MethodDefinition is a pinvoke through the property `HasPInvokeInfo` and if so, access it with the property `PInvokeInfo`.

**Comment by NArnott** [comment]
Good to know.  Thanks for the solution.

**Comment by jbevain** [comment]
🙇






On Fri, Oct 23, 2015 at 6:42 AM -0700, "Nathan Arnott" <notifications@github.com> wrote:












Good to know.  Thanks for the solution.
