### ISSUE TITLE
Losing sequence points through MainModule.Import(method).Resolve() ?

### ISSUE THREAD

**Issue by xoofx** [jbevain/cecil#377]
Hi @jbevain 

I'm hitting a weird issue when trying to use `MethodDefinition.Body.Instructions[].SequencePoint`.

Accessing them directly through a type from the MainModule is fine.

But when I try to get the `MethodDefinition` through a import+resolve from this module, the sequence points are null. Wondering what is wrong...

```
var methodRef = assemblyDefinition.MainModule.Import(methodReflection);
var methodDef = methodRef.Resolve();
// methodDef.Body.Instructions[].SequencePoint are nulls
// While accessing the MethodDefinition directly from assemblyDefinition.MainModule.Types.Methods is fine
```

**Comment by jbevain** [comment]
The first thing I can think of is that if you're not passing your own IAssemblyResolver to your module, you're at risk of getting an assembly loaded by Cecil that is not your module.

As a rule of thumb, for anything not trivial, you should always be in control of the assembly resolution, otherwise it's possible that Resolve will load another ModuleDefinition (without symbols).

Note that Instruction.SequencePoint has been removed in 0.10 which I strongly suggest you use. You can use the notes in http://cecil.pe to figure out the different breaking changes.

What's methodReflection here?

**Comment by xoofx** [comment]
>  IAssemblyResolver to your module

Hm, the AssemblyDefinition is loaded with my own `ReaderParams` + `DefaultAssemblyResolver` so that should be fine no or there is also something special for module?

> What's methodReflection here?

It is a `System.Reflection.MethodInfo`

**Comment by jbevain** [comment]
Have you registered your module into your assembly resolver?

Not exactly sure why this is protected:

https://github.com/jbevain/cecil/blob/master/Mono.Cecil/DefaultAssemblyResolver.cs#L41

But you need to tell the resolver how to resolve this particular module.

**Comment by jbevain** [comment]
Also Import + Resolve is a super weird pattern. Why would you need to create a reference to a method into your module before Resolving it to a MethodDefinition? The Import seems somewhat superfluous.

**Comment by xoofx** [comment]
🎉 The `RegisterAssembly` made the trick (so likely the assembly was loaded 2 times... Thanks!

> Also Import + Resolve is a super weird pattern.

It is mainly because the caller doesn't see that internally I'm using Cecil. So it is passing a MethodInfo to reference a method (and this MethodInfo can contain generic arguments)
