### ISSUE TITLE
ImportReference throws NotImplementedException on core

### ISSUE THREAD

**Issue by Keboo** [jbevain/cecil#505]
I am using [Fody](https://github.com/Fody/Fody) to create a weaver that uses cecil.

When calling `ModuleDefinition.ImportReference(MethodBase)` on .NET Core passing a method from a generic class it throws a NotImplementedException. I believe I am hitting the exception case [here](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/Import.cs#L374-L381) from [here](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/Import.cs#L390-L391). 

For reference I have created a sample repository showing the issue [here](https://github.com/Keboo/CecilIssue) (full disclosure, the referenced dlls are from the distributed Fody NuGet, however the source appears to match for this particular case).

So my question is this, how should I go about getting a `MethodReference` from a `System.Reflection.MethodBase` object in .NET Core?

**Comment by jbevain** [comment]
As a workaround you could work with the Cecil type system and use the ImportReference(MethodReference) overloads.

You could also rebuild Cecil to target .net standard 2.0 and remove the `ifdef` as ResolveMethod should be in the .NET Standard 2.0.

**Comment by Keboo** [comment]
@jbevain thank you for the quick reply. I will look into doing that.

**Comment by jbevain** [comment]
Let's keep that open. I want to move to the .net standard 2 for the next release.

**Comment by SimonCropp** [comment]
@Keboo you should never be converting a methodbase into a methodreference in a fody weaver. Since doing this will leak the build runtime references into the resultant assembly

**Comment by Keboo** [comment]
@SimonCropp thank you, I will make sure to address those. Two follow up questions.

1. Are there any other call like that I should be aware of? Or is there any documentation I can work through?
2. What I am trying to do is invoke a method that has a signature like this: `public void Foo(Action<object> bar)`. Do you have any suggestions on the best way to build up that `Action<>` delegate?

**Comment by atykhyy** [comment]
@SimonCropp That's true if importing with the default assembly importer, but it's very inconvenient. If one has access to the list of `ReferencePath` items MSBuild used to compile the assembly being rewoven, one can search for corresponding framework types in assemblies in that list, as described in my [comments in a different issue](https://github.com/jbevain/cecil/issues/487#issuecomment-377780250). This approach may not be 100% foolproof, but so far it has served me well.

**Comment by jbevain** [comment]
Thanks, that's fixed in master, I'll push a 0.11 with the fix in the coming days.

**Comment by atykhyy** [comment]
A much more robust approach than I described above is to make the reflection and metadata importers handle reference assemblies. If the assembly being processed with Cecil has references from multiple TFMs, MSBuild's `ResolveAssemblyReferences` task adds reference assemblies for those TFMs to the `ReferencePath` item group. The importers should resolve through the type forwarders in the reference assemblies and import the resulting scope rather than the original one. There are a couple sticking points in this solution. First, MSBuild does not always indicate which assemblies are reference assemblies (the `Facade` item metadata is not always generated) and there appears to be no assembly attribute marking reference assemblies. One has to detect them either by path (contains `/ref/`) or by content (`HasExportedTypes` and no types except `<Module>`). The second one is a minor gotcha: `ImportReference(AssemblyNameReference)` creates a metadata table row for every new `AssemblyNameReference`. Careless use of this method when importing cross-TFM scopes can result in metadata table rows for reference assemblies which then confuse the compiler when the rewoven assembly is used as a reference. One must resolve to the correct scope before calling `ImportReference`.
