### ISSUE TITLE
ModuleDefinition.ReadModule hangs permanently

### ISSUE THREAD

**Issue by Metalnem** [jbevain/cecil#555]
**ModuleDefinition.ReadModule** hangs permanently when attempting to read the module from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
ModuleDefinition.ReadModule(path, new ReaderParameters(ReadingMode.Immediate));
```

Found via [SharpFuzz].

[attached archive]: https://github.com/jbevain/cecil/files/2707434/Test.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by rowandh** [comment]
Nice find! This occurs because an entry in the assembly metadata `TypeRef` table of Test.dll is self-referencing. Specifically, entry 11 - `DebuggingModes` has a ResolutionScope of 0x2F (itself).

Cecil does not do any handling of recursive references and will enter an infinite loop while following the references.

**Comment by jbevain** [comment]
Thanks for reporting this.
